### ISSUE TITLE
Quilter should not preview YAML

### ISSUE THREAD

**Issue by johnblommers** [lainsce/quilter#379]
I prefer to put a YAML header in my Markdown files. It should not be displayed in the preview pane. Quilter does display the YAML.

Consider enhancing Quilter to hide the YAML in the preview pane.

Meanwhile the workaround is to remove the YAML block from the Markdown file.

**Comment by lainsce** [comment]
What does the YAML usually contain? It could be useful to use it in some way instead of hiding it.

**Comment by johnblommers** [comment]
Example of YAML I use in my Markdown documents:

```yaml
title: Journal Apps for Linux
author: John Blommers
date: June 7, 2018
toc: true
toc-depth: 4
toccolor: Purple
language: en
```
In practice the YAML is parsed by Pandoc and when generating a PDF from the Markdown it will use the "toc" fields to generate the table of contents.
